### ISSUE TITLE
Switch to System.Text.Json

### ISSUE THREAD

**Issue by kimbirkelund** [ThomasLeschley/Serilog.Sinks.Humio#16]
Hi

Great package 👍We use it extensively in all types of projects.

I was wondering how you'd feel about switch to `System.Text.Json` from `Newtonsoft.Json`? 

I'd be happy to provide a PR for it.

If maintaining backwards compatibility to `netstandard2.0` is important to you (which I think is reasonable enough), I'd suggest pulling the JSON dependency out entirely and put it in separate packages:

 - `Serilog.Sinks.Humio.Core` with just the interface for a serializer
 - `Serilog.Sinks.Humio.SystemTextJson` and `Serilog.Sinks.Humio.NewtonsoftJson` which provides implementations
 - Change `Serilog.Sinks.Humio` to simply be a facade for `Serilog.Sinks.Humio.NewtonsoftJson` to avoid breaking changes

Personally I'd prefer bumping major version to indicate breaking change and make `Serilog.Sinks.Humio` use `System.Text.Json` as the default implementation while providing a `Serilog.Sinks.Humio.NewtonsoftJson` for those that really want it.

I'd also suggest making the serialization options customizable while we're at it.

**Comment by ThomasWillumsen** [comment]
Hey

Thanks and I totally agree. It is time to make the switch to `System.Text.Json` 🙂
I will have time to look at it this weekend. If you need it before then feel free to make a PR.

Bumping major version with breaking change seems to be the way to go about it IMO.

It does seem like `System.Text.Json` is supported in netstandard2.0 [(src)](https://learn.microsoft.com/en-us/dotnet/standard/serialization/system-text-json/overview?pivots=dotnet-6-0#how-to-get-the-library), so I wonder if it's even necessary to bother with a newtonsoft implementation.

**Comment by ThomasWillumsen** [comment]
Version 2.0.0 is out now 😎

**Comment by kimbirkelund** [comment]
Great :-)
