### ISSUE TITLE
restrictedToMinimumLevel

### ISSUE THREAD

**Issue by SQLDBGuru** [ThomasLeschley/Serilog.Sinks.Humio#22]
Doesn't appear to be a valid argument????  Or Where does it actually go for the humio sink?

ie I want everything to go to a file sink, and I only want Error (and Greater) to go to Humio.

Thank you!

**Comment by ThomasWillumsen** [comment]
Hey! I don't believe i have built support for restrictedToMinimumLevel but i can take a look at it later this week or next week 🙂
If you need it sooner, you are more than welcome to open a PR.

Regards, Thomas

**Comment by SQLDBGuru** [comment]
Thank you…   I am not familiar with the structures of creating a serilog sink but I will take a peek once I can as well…

I assume that using the restricted.. is really the only want to do what I am trying to do???

Jeff

**Comment by ThomasWillumsen** [comment]
Yes it is the right way to do it. It is documented [here](https://github.com/serilog/serilog/wiki/Configuration-Basics#overriding-per-sink) 
I am not aware of any other approaches.

**Comment by ThomasWillumsen** [comment]
@SQLDBGuru Hi Jeff, I have published a new version 2.0.1 of the nuget package which supports restrictedToMinimumLevel.
Let me know if any other issues arise.

Regards, Thomas

**Comment by SQLDBGuru** [comment]
Great!!!   Thank you!
