### ISSUE TITLE
appsettings.json configuration

### ISSUE THREAD

**Issue by dmonkey75** [ThomasLeschley/Serilog.Sinks.Humio#5]
Hello,

does it support appsettings.json configuration?

example:
{
  "Serilog": {
    "WriteTo": [
      {
          "Name": "Humio",
          "IngestToken": "{token}"
      }
    ]
  }
}

**Comment by ThomasWillumsen** [comment]
Hi! That is a good question🙂
I haven't tested for this - I'm guessing it doesn't work.
Are you using the Serilog.Settings.Configuration package for this?

**Comment by dmonkey75** [comment]
Hi @ThomasLeschley... yes! that package... looks I am gonna stick using the one you have which via code... thank you. : )

**Comment by ThomasWillumsen** [comment]
Great! I'm still gonna take a look at it though over the Christmas holidays because I want to support Serilog.Settings.Configuration.
